/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WelcomeRouteImport } from "./routes/welcome"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ScoringLeagueIdRouteImport } from "./routes/scoring.$leagueId"

const WelcomeRoute = WelcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/welcome.lazy").then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringLeagueIdRoute = ScoringLeagueIdRouteImport.update({
  id: "/scoring/$leagueId",
  path: "/scoring/$leagueId",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import("./routes/scoring.$leagueId.lazy").then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/welcome": typeof WelcomeRoute
  "/scoring/$leagueId": typeof ScoringLeagueIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/welcome": typeof WelcomeRoute
  "/scoring/$leagueId": typeof ScoringLeagueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/welcome": typeof WelcomeRoute
  "/scoring/$leagueId": typeof ScoringLeagueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/welcome" | "/scoring/$leagueId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/welcome" | "/scoring/$leagueId"
  id: "__root__" | "/" | "/welcome" | "/scoring/$leagueId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  ScoringLeagueIdRoute: typeof ScoringLeagueIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/welcome": {
      id: "/welcome"
      path: "/welcome"
      fullPath: "/welcome"
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scoring/$leagueId": {
      id: "/scoring/$leagueId"
      path: "/scoring/$leagueId"
      fullPath: "/scoring/$leagueId"
      preLoaderRoute: typeof ScoringLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  ScoringLeagueIdRoute: ScoringLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
